### ISSUE TITLE
log level set to debug by default

### ISSUE THREAD

**Issue by raffenet** [RIKEN-SysSoft/uti#2]
https://github.com/RIKEN-SysSoft/uti/blob/a5fed93af9387f663d60ed9650fab0a2026bcdfe/src/common.c#L6

It would be nice for a default build to not output debug information. A runtime mechanism (e.g. environment variable) to control the log level would also be useful.

**Comment by masamichitakagi** [comment]
I changed it to UTI_LOGLEVEL_WARN and made it configurable through environmental variable UTI_LOGLEVEL.

**Comment by raffenet** [comment]
Looks good 👍.
